services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    environment:
      - JENKINS_URL=${JENKINS_URL}
      - JENKINS_AGENT_NAME=${JENKINS_AGENT_NAME}
      - JENKINS_SECRET=${JENKINS_SECRET}
    depends_on:
      - jenkins

  consul:
    image: hashicorp/consul:1.16.2
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: "agent -dev -client=0.0.0.0"
    volumes:
      - consul_data:/consul/data
    restart: unless-stopped

  vault:
    image: hashicorp/vault:1.15.3
    container_name: vault
    restart: unless-stopped
    ports:
      - "8300:8300"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: "http://0.0.0.0:8300"
      VAULT_LOCAL_CONFIG: |
        {
          "backend": {
            "file": {
              "path": "/vault/file"
            }
          },
          "listener": {
            "tcp": {
              "address": "0.0.0.0:8300",
              "tls_disable": 1
            }
          },
          "ui": true
        }
    volumes:
      - vault_data:/vault/file

volumes:
  jenkins_home:
    external: true
    name: devops-lab_jenkins_home

  consul_data:
    external: true
    name: devops-lab_consul_data

  vault_data:
    external: true
    name: devops-lab_vault_data

